import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


function Header() {
  return (
    <header className="bg-slate-500 py-4">
      <div className="Container mx-auto px-4">
        <nav className ="flex items-center justify-between">
          <div className ="flex items-center">
            <Link href= "/">Snowtooth Mountain</Link>
          </div>
          <div className ="flex items-center">
            <Link href= "/mountain">Mountain Info</Link>
          </div>
          <div className ="flex items-center">
            <Link href= "/hotels">Hotels</Link>
          </div>
          <div className ="flex items-center">
            <Link href="/contact">Conact Us</Link>
          </div>
        </nav>
      </div>
    </header>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
